// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.1.0.
// **********************************************************************

#ifndef __RETCODE_H_
#define __RETCODE_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
using namespace std;


namespace Tseer
{
    const tars::Int32 TSEER_SERVERSUCCESS = 0;

    const tars::Int32 TSEER_UNKNOW_ERROR = -99;

    const tars::Int32 TSEER_REGISTRY_UNKNOWN = 2000;

    const tars::Int32 TSEER_REGISTRY_PARAM_ERROR = 2001;

    const tars::Int32 TSEER_REGISTRY_UPDATESERVER_PARAM_ERROR = 2002;

    const tars::Int32 TSEER_REGISTRY_GETSERVER_PARAM_ERROR = 2003;

    const tars::Int32 TSEER_REGISTRY_SETSERVER_PARAM_ERROR = 2004;

    const tars::Int32 TSEER_REGISTRY_DELTESERVER_PARAM_ERROR = 2005;

    const tars::Int32 TSEER_REGISTRY_ADDSERVER_PARAM_ERROR = 2005;

    const tars::Int32 TSEER_REGISTRY_ETCD_UNKNOWN = 2500;

    const tars::Int32 TSEER_REGISTRY_ETCD_PARSE_JSON_FAIL = 2501;

    const tars::Int32 TSEER_REGISTRY_ETCD_TIMEOUT = 2502;

    const tars::Int32 TSEER_REGISTRY_ETCD_RET_ERROR = 2503;

    const tars::Int32 TSEER_REGISTRY_ETCD_DATA_NOTFOUND = 2504;

    const tars::Int32 TSEER_REGISTRY_ETCD_SEND_REQ_FAIL = 2505;


}



#endif
